### ISSUE TITLE
Support for selecting continuous lines until the first empty line before or after the current cursor position.

### ISSUE THREAD

**Issue by theSprog** [nachocab/vscode-select-paragraph#10]
Description:
Currently, the plugin provides excellent functionality for various selections, but I would like to propose an enhancement that would make it even more versatile and aligned with Vim-like behavior.

Use Case:
In Vim, the { and } motion commands allow users to navigate and select continuous lines until the first empty line in both forward and backward directions. This is extremely useful when working with structured text or code.

Request:
I kindly request the addition of a similar feature to this plugin. Specifically, I would like the ability to:

Select continuous lines until the first empty line before the current cursor position using a custom key binding or command.
Select continuous lines until the first empty line after the current cursor position using a custom key binding or command.

**Comment by nachocab** [comment]
This extension is no longer updated. I recommend you check out this one: https://github.com/aronwoost/sublime-expand-region
